
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 19 00:29:19 CST 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 13;
  public static final int PUNTO_COMA = 14;
  public static final int OPERADOR_ASIGNACION = 10;
  public static final int NUMERO_ENTERO = 6;
  public static final int PALABRA_RESERVADA = 7;
  public static final int EOF = 0;
  public static final int ACCION = 4;
  public static final int ESPACIO = 15;
  public static final int CONTROL_GARRA = 5;
  public static final int error = 1;
  public static final int DESCONOCIDO = 16;
  public static final int PARENTESIS_C = 12;
  public static final int OPERADOR_PUNTO = 9;
  public static final int PARENTESIS_A = 11;
  public static final int METODO = 3;
  public static final int COMENTARIO = 8;
  public static final int IDENTIFICADOR = 2;
}

